export type ThemeName = 'light' | 'dark' | 'blue' | 'gold' | 'pink' | 'green' | 'gray' | 'purple';

export interface ThemeColors {
  background: string;
  backgroundDeep: string;
  surface: string;
  insetFill: string;
  shadowLight: string;
  shadowDark: string;
  textPrimary: string;
  textMuted: string;
  accent: string;
  accentSoft: string;
  insetBorderDark: string;
  insetBorderLight: string;
  iosBg: string;
  iosSeparator: string;
  iosBlue: string;
  iosRed: string;
  iosGreen: string;
  iosGray: string;
  iosLabel: string;
  iosSecondaryLabel: string;
}

export interface Theme {
  name: ThemeName;
  label: string;
  colors: ThemeColors;
  radii: {
    card: number;
    panel: number;
    pill: number;
    iconBtn: number;
    dayBtn: number;
  };
  spacing: {
    xs: number;
    sm: number;
    md: number;
    lg: number;
    xl: number;
  };
  typography: {
    title: { fontWeight: '700'; fontSize: number; letterSpacing: number };
    subtitle: { fontWeight: '500'; fontSize: number };
    label: { fontWeight: '700'; fontSize: number };
    dayNumber: { fontWeight: '700'; fontSize: number };
  };
  isDark: boolean;
}

const radii = {
  card: 28,
  panel: 18,
  pill: 16,
  iconBtn: 14,
  dayBtn: 999,
};

const spacing = {
  xs: 4,
  sm: 8,
  md: 14,
  lg: 20,
  xl: 26,
};

const typography = {
  title: { fontWeight: '700' as const, fontSize: 21, letterSpacing: -0.2 },
  subtitle: { fontWeight: '500' as const, fontSize: 13 },
  label: { fontWeight: '700' as const, fontSize: 12 },
  dayNumber: { fontWeight: '700' as const, fontSize: 14 },
};

export const themes: Record<ThemeName, Theme> = {
  light: {
    name: 'light',
    label: 'White Neumorphic',
    colors: {
      background: '#E6E9EF',
      backgroundDeep: '#DDE1E8',
      surface: '#E6E9EF',
      insetFill: '#DADFE7',
      shadowLight: '#FFFFFF',
      shadowDark: '#B3BBC9',
      textPrimary: '#3A4250',
      textMuted: '#96A0B2',
      accent: '#EF6F6F',
      accentSoft: '#F7D7D7',
      insetBorderDark: 'rgba(150,160,178,0.55)',
      insetBorderLight: 'rgba(255,255,255,0.7)',
      iosBg: '#F2F2F7',
      iosSeparator: '#ffffff',
      iosBlue: '#007AFF',
      iosRed: '#FF3B30',
      iosGreen: '#34C759',
      iosGray: '#8E8E93',
      iosLabel: '#1C1C1E',
      iosSecondaryLabel: '#8E8E93',
    },
    radii,
    spacing,
    typography,
    isDark: false,
  },
  dark: {
    name: 'dark',
    label: 'Dark Neumorphic',
    colors: {
      background: '#1E1E1E',
      backgroundDeep: '#181818',
      surface: '#1E1E1E',
      insetFill: '#252525',
      shadowLight: '#2C2C2C',
      shadowDark: '#0F0F0F',
      textPrimary: '#E8E8E8',
      textMuted: '#9E9E9E',
      accent: '#EF6F6F',
      accentSoft: '#3A2020',
      insetBorderDark: 'rgba(0,0,0,0.55)',
      insetBorderLight: 'rgba(255,255,255,0.08)',
      iosBg: '#1C1C1E',
      iosSeparator: '#38383A',
      iosBlue: '#0A84FF',
      iosRed: '#FF453A',
      iosGreen: '#30D158',
      iosGray: '#8E8E93',
      iosLabel: '#FFFFFF',
      iosSecondaryLabel: '#98989E',
    },
    radii,
    spacing,
    typography,
    isDark: true,
  },
  blue: {
    name: 'blue',
    label: 'Ocean Blue',
    colors: {
      background: '#D6E2F2',
      backgroundDeep: '#CBD9ED',
      surface: '#D6E2F2',
      insetFill: '#C6D6EC',
      shadowLight: '#F8F8F9',
      shadowDark: '#97B3D8',
      textPrimary: '#2A3348',
      textMuted: '#8892A8',
      accent: '#5B7FFF',
      accentSoft: '#D6E0FF',
      insetBorderDark: 'rgba(120,148,182,0.55)',
      insetBorderLight: 'rgba(248,248,249,0.7)',
      iosBg: '#F2F2F7',
      iosSeparator: '#ffffff',
      iosBlue: '#5B7FFF',
      iosRed: '#FF3B30',
      iosGreen: '#34C759',
      iosGray: '#8E8E93',
      iosLabel: '#1C1C1E',
      iosSecondaryLabel: '#8E8E93',
    },
    radii,
    spacing,
    typography,
    isDark: false,
  },
  pink: {
    name: 'pink',
    label: 'Blush Pink',
    colors: {
      background: '#EDC6D8',
      backgroundDeep: '#E8BBD0',
      surface: '#EDC6D8',
      insetFill: '#E7B6CD',
      shadowLight: '#EFEDEE',
      shadowDark: '#D387AA',
      textPrimary: '#3D2E36',
      textMuted: '#9A8892',
      accent: '#E87A8A',
      accentSoft: '#F8E0E4',
      insetBorderDark: 'rgba(190,120,150,0.55)',
      insetBorderLight: 'rgba(239,237,238,0.7)',
      iosBg: '#E8BBD0',
      iosSeparator: '#E5E5EA',
      iosBlue: '#E87A8A',
      iosRed: '#FF3B30',
      iosGreen: '#34C759',
      iosGray: '#8E8E93',
      iosLabel: '#1C1C1E',
      iosSecondaryLabel: '#8E8E93',
    },
    radii,
    spacing,
    typography,
    isDark: false,
  },
  green: {
    name: 'green',
    label: 'Sage Green',
    colors: {
      background: '#D8ECD8',
      backgroundDeep: '#CEE6CE',
      surface: '#D8ECD8',
      insetFill: '#CAE4CA',
      shadowLight: '#F6F7F6',
      shadowDark: '#A0CAA0',
      textPrimary: '#2A3D2A',
      textMuted: '#829982',
      accent: '#6BBF6B',
      accentSoft: '#E0F5E0',
      insetBorderDark: 'rgba(130,170,130,0.55)',
      insetBorderLight: 'rgba(246,247,246,0.7)',
      iosBg: '#F2F2F7',
      iosSeparator: '#ffffff',
      iosBlue: '#6BBF6B',
      iosRed: '#FF3B30',
      iosGreen: '#34C759',
      iosGray: '#8E8E93',
      iosLabel: '#1C1C1E',
      iosSecondaryLabel: '#8E8E93',
    },
    radii,
    spacing,
    typography,
    isDark: false,
  },
  gray: {
    name: 'gray',
    label: 'Cool Gray',
    colors: {
      background: '#E4E6E9',
      backgroundDeep: '#DCDEE1',
      surface: '#E4E6E9',
      insetFill: '#D8DBDF',
      shadowLight: '#FBFBFB',
      shadowDark: '#B7B9BD',
      textPrimary: '#2C2E33',
      textMuted: '#85888F',
      accent: '#7A8294',
      accentSoft: '#E2E5EA',
      insetBorderDark: 'rgba(148,151,157,0.55)',
      insetBorderLight: 'rgba(251,251,251,0.7)',
      iosBg: '#F2F2F7',
      iosSeparator: '#ffffff',
      iosBlue: '#7A8294',
      iosRed: '#FF3B30',
      iosGreen: '#34C759',
      iosGray: '#8E8E93',
      iosLabel: '#1C1C1E',
      iosSecondaryLabel: '#8E8E93',
    },
    radii,
    spacing,
    typography,
    isDark: false,
  },
  purple: {
    name: 'purple',
    label: 'Lavender Purple',
    colors: {
      background: '#E2D2F0',
      backgroundDeep: '#DAC7EB',
      surface: '#E2D2F0',
      insetFill: '#D7C2EA',
      shadowLight: '#F5F5F6',
      shadowDark: '#B794D5',
      textPrimary: '#312A40',
      textMuted: '#8E82A0',
      accent: '#9B7FD4',
      accentSoft: '#EBE0F8',
      insetBorderDark: 'rgba(158,124,190,0.55)',
      insetBorderLight: 'rgba(245,245,246,0.7)',
      iosBg: '#DAC7EB',
      iosSeparator: '#E5E5EA',
      iosBlue: '#9B7FD4',
      iosRed: '#FF3B30',
      iosGreen: '#34C759',
      iosGray: '#8E8E93',
      iosLabel: '#1C1C1E',
      iosSecondaryLabel: '#8E8E93',
    },
    radii,
    spacing,
    typography,
    isDark: false,
  },
  gold: {
    name: 'gold',
    label: 'Sunset Gold',
    colors: {
      background: '#F0E6C8',
      backgroundDeep: '#EBE0BC',
      surface: '#F0E6C8',
      insetFill: '#EBDEB7',
      shadowLight: '#F2F1EF',
      shadowDark: '#D8C487',
      textPrimary: '#3D352A',
      textMuted: '#9E9485',
      accent: '#D4A545',
      accentSoft: '#F5EDD6',
      insetBorderDark: 'rgba(198,168,110,0.55)',
      insetBorderLight: 'rgba(242,241,239,0.7)',
      iosBg: '#EBE0BC',
      iosSeparator: '#ffffff',
      iosBlue: '#D4A545',
      iosRed: '#FF3B30',
      iosGreen: '#34C759',
      iosGray: '#8E8E93',
      iosLabel: '#1C1C1E',
      iosSecondaryLabel: '#8E8E93',
    },
    radii,
    spacing,
    typography,
    isDark: false,
  },
};

// export const themes: Record<ThemeName, Theme> = {
//   light: {
//     name: 'light',
//     label: 'White Neumorphic',
//     colors: {
//       background: '#E6E9EF',
//       backgroundDeep: '#DDE1E8',
//       surface: '#E6E9EF',
//       insetFill: '#DADFE7',
//       shadowLight: '#FFFFFF',
//       shadowDark: '#B3BBC9',
//       textPrimary: '#3A4250',
//       textMuted: '#96A0B2',
//       accent: '#EF6F6F',
//       accentSoft: '#F7D7D7',
//       insetBorderDark: 'rgba(150,160,178,0.55)',
//       insetBorderLight: 'rgba(255,255,255,0.7)',
//       iosBg: '#F2F2F7',
//       iosSeparator: '#E5E5EA',
//       iosBlue: '#007AFF',
//       iosRed: '#FF3B30',
//       iosGreen: '#34C759',
//       iosGray: '#8E8E93',
//       iosLabel: '#1C1C1E',
//       iosSecondaryLabel: '#8E8E93',
//     },
//     radii,
//     spacing,
//     typography,
//     isDark: false,
//   },
//   dark: {
//     name: 'dark',
//     label: 'Dark Neumorphic',
//     colors: {
//       background: '#1E1E1E',
//       backgroundDeep: '#181818',
//       surface: '#1E1E1E',
//       insetFill: '#252525',
//       shadowLight: '#2C2C2C',
//       shadowDark: '#0F0F0F',
//       textPrimary: '#E8E8E8',
//       textMuted: '#9E9E9E',
//       accent: '#EF6F6F',
//       accentSoft: '#3A2020',
//       insetBorderDark: 'rgba(0,0,0,0.55)',
//       insetBorderLight: 'rgba(255,255,255,0.08)',
//       iosBg: '#1C1C1E',
//       iosSeparator: '#38383A',
//       iosBlue: '#0A84FF',
//       iosRed: '#FF453A',
//       iosGreen: '#30D158',
//       iosGray: '#8E8E93',
//       iosLabel: '#FFFFFF',
//       iosSecondaryLabel: '#98989E',
//     },
//     radii,
//     spacing,
//     typography,
//     isDark: true,
//   },
//   blue: {
//     name: 'blue',
//     label: 'Ocean Blue',
//     colors: {
//       background: '#D6E2F2',
//       backgroundDeep: '#CAD8EC',
//       surface: '#D6E2F2',
//       insetFill: '#C0D0E6',
//       shadowLight: '#ECF2FA',
//       shadowDark: '#96ADC8',
//       textPrimary: '#2A3348',
//       textMuted: '#8892A8',
//       accent: '#5B7FFF',
//       accentSoft: '#D6E0FF',
//       insetBorderDark: 'rgba(150,168,190,0.55)',
//       insetBorderLight: 'rgba(236,242,250,0.7)',
//       iosBg: '#F2F2F7',
//       iosSeparator: '#E5E5EA',
//       iosBlue: '#5B7FFF',
//       iosRed: '#FF3B30',
//       iosGreen: '#34C759',
//       iosGray: '#8E8E93',
//       iosLabel: '#1C1C1E',
//       iosSecondaryLabel: '#8E8E93',
//     },
//     radii,
//     spacing,
//     typography,
//     isDark: false,
//   },
//   pink: {
//     name: 'pink',
//     label: 'Blush Pink',
//     colors: {
//       background: '#EDC6D8',
//       backgroundDeep: '#E3B8CC',
//       surface: '#EDC6D8',
//       insetFill: '#DBAEC4',
//       shadowLight: '#FADCE8',
//       shadowDark: '#BD8DA3',
//       textPrimary: '#3D2E36',
//       textMuted: '#9A8892',
//       accent: '#E87A8A',
//       accentSoft: '#F8E0E4',
//       insetBorderDark: 'rgba(180,140,158,0.55)',
//       insetBorderLight: 'rgba(250,220,232,0.7)',
//       iosBg: '#F2F2F7',
//       iosSeparator: '#E5E5EA',
//       iosBlue: '#E87A8A',
//       iosRed: '#FF3B30',
//       iosGreen: '#34C759',
//       iosGray: '#8E8E93',
//       iosLabel: '#1C1C1E',
//       iosSecondaryLabel: '#8E8E93',
//     },
//     radii,
//     spacing,
//     typography,
//     isDark: false,
//   },
//   green: {
//     name: 'green',
//     label: 'Sage Green',
//     colors: {
//       background: '#D8ECD8',
//       backgroundDeep: '#CAE2CA',
//       surface: '#D8ECD8',
//       insetFill: '#BED8BE',
//       shadowLight: '#ECF5EC',
//       shadowDark: '#9CC49C',
//       textPrimary: '#2A3D2A',
//       textMuted: '#829982',
//       accent: '#6BBF6B',
//       accentSoft: '#E0F5E0',
//       insetBorderDark: 'rgba(155,185,155,0.55)',
//       insetBorderLight: 'rgba(236,245,236,0.7)',
//       iosBg: '#F2F2F7',
//       iosSeparator: '#E5E5EA',
//       iosBlue: '#6BBF6B',
//       iosRed: '#FF3B30',
//       iosGreen: '#34C759',
//       iosGray: '#8E8E93',
//       iosLabel: '#1C1C1E',
//       iosSecondaryLabel: '#8E8E93',
//     },
//     radii,
//     spacing,
//     typography,
//     isDark: false,
//   },
//   gray: {
//     name: 'gray',
//     label: 'Cool Gray',
//     colors: {
//       background: '#E4E6E9',
//       backgroundDeep: '#D8DADE',
//       surface: '#E4E6E9',
//       insetFill: '#D0D2D6',
//       shadowLight: '#F5F5F7',
//       shadowDark: '#A8ABB0',
//       textPrimary: '#2C2E33',
//       textMuted: '#85888F',
//       accent: '#7A8294',
//       accentSoft: '#E2E5EA',
//       insetBorderDark: 'rgba(160,162,168,0.55)',
//       insetBorderLight: 'rgba(245,245,247,0.7)',
//       iosBg: '#F2F2F7',
//       iosSeparator: '#E5E5EA',
//       iosBlue: '#7A8294',
//       iosRed: '#FF3B30',
//       iosGreen: '#34C759',
//       iosGray: '#8E8E93',
//       iosLabel: '#1C1C1E',
//       iosSecondaryLabel: '#8E8E93',
//     },
//     radii,
//     spacing,
//     typography,
//     isDark: false,
//   },
//   purple: {
//     name: 'purple',
//     label: 'Lavender Purple',
//     colors: {
//       background: '#E2D2F0',
//       backgroundDeep: '#D8C4E8',
//       surface: '#E2D2F0',
//       insetFill: '#CEB8E0',
//       shadowLight: '#F0E6F8',
//       shadowDark: '#AA8EC4',
//       textPrimary: '#312A40',
//       textMuted: '#8E82A0',
//       accent: '#9B7FD4',
//       accentSoft: '#EBE0F8',
//       insetBorderDark: 'rgba(168,148,188,0.55)',
//       insetBorderLight: 'rgba(240,230,248,0.7)',
//       iosBg: '#F2F2F7',
//       iosSeparator: '#E5E5EA',
//       iosBlue: '#9B7FD4',
//       iosRed: '#FF3B30',
//       iosGreen: '#34C759',
//       iosGray: '#8E8E93',
//       iosLabel: '#1C1C1E',
//       iosSecondaryLabel: '#8E8E93',
//     },
//     radii,
//     spacing,
//     typography,
//     isDark: false,
//   },
//   gold: {
//     name: 'gold',
//     label: 'Sunset Gold',
//     colors: {
//       background: '#F0E6C8',
//       backgroundDeep: '#E6DAB6',
//       surface: '#F0E6C8',
//       insetFill: '#DCCEA6',
//       shadowLight: '#FCF5E0',
//       shadowDark: '#BBA47A',
//       textPrimary: '#3D352A',
//       textMuted: '#9E9485',
//       accent: '#D4A545',
//       accentSoft: '#F5EDD6',
//       insetBorderDark: 'rgba(180,162,128,0.55)',
//       insetBorderLight: 'rgba(252,245,224,0.7)',
//       iosBg: '#F2F2F7',
//       iosSeparator: '#E5E5EA',
//       iosBlue: '#D4A545',
//       iosRed: '#FF3B30',
//       iosGreen: '#34C759',
//       iosGray: '#8E8E93',
//       iosLabel: '#1C1C1E',
//       iosSecondaryLabel: '#8E8E93',
//     },
//     radii,
//     spacing,
//     typography,
//     isDark: false,
//   },
// };
