# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'Habita' do
  use_modular_headers!
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    # Add Crashlytics dSYM upload script phase to main app target
    require 'xcodeproj'
    project_path = Pod::Config.instance.installation_root + 'Habita.xcodeproj'
    user_project = Xcodeproj::Project.open(project_path)

    user_project.targets.each do |target|
      next unless target.name == 'Habita'

      has_phase = target.build_phases.any? { |p|
        p.respond_to?(:name) && p.name == 'Upload Crashlytics dSYMs'
      }

      unless has_phase
        phase = target.new_shell_script_build_phase('Upload Crashlytics dSYMs')
        phase.shell_script = "\"${PODS_ROOT}/FirebaseCrashlytics/run\"\n"
        phase.input_paths = [
          '${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}',
          '${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Resources/DWARF/${PRODUCT_NAME}',
          '${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Info.plist',
          '$(TARGET_BUILD_DIR)/$(UNLOCALIZED_RESOURCES_FOLDER_PATH)/GoogleService-Info.plist',
          '$(TARGET_BUILD_DIR)/$(EXECUTABLE_PATH)',
        ]
      end
    end

    user_project.save
  end
end
